Repository Blaze-Stars/Image-Filter-Application, pull requests merged in 2022-06, with the labels that each got.

#44 File Handling in main.cpp (using try catch block)
  main.cpp
Labels: Important

#42 Function prototype for different filters
  helpers.h
Labels: Important

#46 structures added
  bmp.h
Labels: duplicate, Important

#50 Code for blur filter
  helpers.cpp
Labels: enhancement

#51 Added code for Reflect filter
  helpers.cpp
Labels: enhancement

#52 Static Casting and Exception Handling
  helpers.cpp
  main.cpp
Labels: enhancement, Important

#54 Changed `Image-Filter-Beta` to `Image-Filter-Application`
  README.md
Labels: documentation

#55 Improved Documentation for Image-Filter-Application
  README.md
Labels: documentation
